services:
  fusion-revive:
    container_name: fusion-revive
    build: .
    volumes:
      - ~/Developer/fusion-revive/data:/app/data
    network_mode: bridge
    ports:
      - 5050:5050
    environment:
      TZ: Europe/Stockholm
      HASS_URL: http://192.168.1.241:8123
    restart: always
# cd ~/Developer/fusion-revive && docker-compose -f compose-dev.yml up -d --build fusion-revive
